# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'spotify' do
  use_frameworks!

  pod 'SDWebImage'
  pod 'Appirater'
  pod 'FirebaseAnalytics'

end
